### ISSUE TITLE
please man, let me fork this. 

### ISSUE THREAD

**Issue by VeH-c** [Bluscream/bluscream#1]
i had many of the Themes in https://github.com/Jiiks/BetterDiscordApp/wiki/Themes linked to your removed repo, many can be found no where else. what ever is going on in your life please consider letting me save these Plugins & Themes. i don't get why people do this but what is is what is, there is no changing that. Peace!

**Comment by Bluscream** [comment]
Which repo do you need exactly?

**Comment by VeH-c** [comment]
> /Bluscream/BetterDiscord-Themes/master/

here are the six linked.
https://raw.githubusercontent.com/Bluscream/BetterDiscord-Themes/master/Blocky%20Green.theme.css
https://raw.githubusercontent.com/Bluscream/BetterDiscord-Themes/master/Discord%20Clear%20Blue.theme.css
https://raw.githubusercontent.com/Bluscream/BetterDiscord-Themes/master/Discord%20Helpfull%20Icons.theme.css
https://raw.githubusercontent.com/Bluscream/BetterDiscord-Themes/master/Discord%20Rounded%20Glass.theme.css
(https://raw.githubusercontent.com/Bluscream/BetterDiscord-Themes/master/Discord%20Twitchcord.theme.css
https://raw.githubusercontent.com/Bluscream/BetterDiscord-Themes/master/XP.theme.css

let it be known a will gladly clone any of your Better Discord Repo's, i don't even care if **only** i care about your Repo's, thats all i need. you don't participate what you have until it's in gone...

**Comment by Bluscream** [comment]
https://github.com/Bluscream/BetterDiscord-Themes here u go
