### ISSUE TITLE
Da habe ich doch nochmal eine Frage ^^

### ISSUE THREAD

**Issue by Kirossos** [Bluscream/bluscream#2]
Hi,

ich wollte dich mal fragen, ob dir da was Schlaues einfällt.
Ich habe das Problem, das ich versucht habe die Client Beschreibung zu setzen, aber das ging nicht, weil das eine Invalid Flag ist zum Festsetzen.

Jetzt habe ich die Meta Data genommen, Problem ist das andere Clients kein update darüber bekommen das sich die Meta Data geändert hat ^^

Irgend eine Idee wie ich eine andere Methode nutzen könnte, denn selbst für Whisperlisten brauche ich eine Möglichkeit das andere seine Gruppenzugehörigkeit sehen können.

Servergruppen würde ich nur ungern benutzen wollen ^^

**Comment by Bluscream** [comment]
Ist es wichtig das heute zu klären? Hab mich grad ins bett gelegt ^^

**Comment by Bluscream** [comment]
Btw: Join the chat: https://gitter.im/Bluscream/Teamspeak-Plugins

**Comment by Bluscream** [comment]
So bin da @Kirossos ^^

**Comment by Bluscream** [comment]
immernoch da :dagger:

**Comment by Kirossos** [comment]
Sorry war mit meiner Freundin unterwegs ^^
Also ich wäre ab jetzt auch wieder da :p

**Comment by Kirossos** [comment]
Ich halte jetzt auch diesen Thread im Auge also wenn du kurz dafür zeit hast, melde dich einfach :)

**Comment by Bluscream** [comment]
hab theoretisch zeit

**Comment by Kirossos** [comment]
Ich fange langsam an Github zu hassen, der hat mir deine Nachricht erst angezeigt, als ich meine abgeschickt habe ....

**Comment by Kirossos** [comment]
hätteste jetzt nochmal eben zeit, sorry? ^^

**Comment by Bluscream** [comment]
Theoretisch ja

**Comment by Kirossos** [comment]
Also ich geh einfach auf unseren TS und wenn du zeit hast, kannst du ja vorbei schauen :)

**Comment by Bluscream** [comment]
Das wird wahrscheinlich nix, mein windoof hat vorhin den geist aufgegeben sorry ;-;

**Comment by Bluscream** [comment]
Ich behalte dich aber im hinterkopf und komm auf dich zu sobald ichs wieder gefixt hab ^^

**Comment by Kirossos** [comment]
Ja kein Stress :)

**Comment by Bluscream** [comment]
So PC geht wieder, sei so lieb und sach nochmal die IP ^^
